import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import UpNav from '../Components/UpNav'
import Nav from '../Components/Nav'
import MobileNav from '../Components/MobileNav'
import Carousel from '../Components/Carousel'
import Jobs from '../Components/Jobs'
import MobileJobs from '../Components/MobileJobs'
import CardContainer from '../Components/CardContainer'
import Motor from '../Components/Motor'
import Daftarche from '../Components/Daftarche'
import DaftarcheMobile from '../Components/DaftarcheMobile'
import LogoSlider from '../Components/LogoSlider'
import LogoSliderMobile from '../Components/LogoSliderMobile'
import Footer from '../Components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
        <link rel="icon" href="/favicon.ico" />
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      </Head>

      <main>
        <UpNav />
        <Nav />
        <MobileNav />
        <Carousel />
        <Jobs />
        <MobileJobs />
        <CardContainer />
        <Motor />
        <Daftarche />
        <DaftarcheMobile />
        <LogoSlider />
        <LogoSliderMobile />
        <Footer />
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
